# Generated by Django 2.2.13 on 2020-06-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Рубашки'), ('SW', 'Спортивная одежда'), ('OW', 'Верхняя одежда')], max_length=2),
        ),
    ]
