# Generated by Django 2.2.13 on 2020-07-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200621_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_intent_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
