# Generated by Django 2.2.13 on 2020-07-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payment_paymnet_succeeded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paymnet_succeeded',
            new_name='payment_succeeded',
        ),
    ]
