# Generated by Django 2.2.13 on 2020-07-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200711_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
